name: React CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/demodeploy-fe .

      - name: DockerHub Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/demodeploy-fe

      - name: Sunucuya Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/demodeploy-fe
            docker stop demo-fe || true
            docker rm demo-fe || true
            docker run -d --name demo-fe -p 3000:80 ${{ secrets.DOCKERHUB_USERNAME }}/demodeploy-fe
