name: React CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Al
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Image Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-frontend .

      - name: DockerHub Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-frontend

      - name: Sunucuya Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-frontend
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/react-frontend
